### ISSUE TITLE
Gap Analysis: chrome-debug vs. node-debug

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-node-cdp-debug#1]
**Goal**: Find out what is needed to use the 'Debugger for Chrome' extension as a replacement for 'Node Debug'.

Installation of node 7.0:
```
	npm install -g node-nightly
	node-nightly --version
```

Install experimental CDP extension:
```
	git clone https://github.com/Microsoft/vscode-node-cdp-debug
	cd vscode-node-cdp-debug
	npm install
	code .
```

Run node 7.0 in 'inspect' mode:
```
	node-nightly --inspect index.js
```

Findings:
* Startup:
  - [ ] no "launch" support - #2
  - [ ] no "restart" on attach - #3
  - [ ] no extension host support - #4
  - [ ] early breakpoints on startup don't work because debugger does not break on entry by default - #5
  - [ ] Support a UI picker of all available targets - Microsoft/vscode-chrome-debug-core#19
  - [ ] Support runInTerminalRequest - #6
* Variables:
  - [ ] properties with getters not supported - Microsoft/vscode-chrome-debug-core#77
  - [x] array sorting wrong (alphabetically instead of numerical) - Microsoft/vscode-chrome-debug-core#62
  - [ ] large arrays slow: no paging ('chunks')
     (needs adoption of VS Code variables paging) - Microsoft/vscode-chrome-debug-core#4
  - [ ] setting variable values - Microsoft/vscode-chrome-debug-core#58
* ES6:
  - [ ] no Map support - Microsoft/vscode-chrome-debug-core#31
  - [ ] no Set support - Microsoft/vscode-chrome-debug-core#31
  - [ ] no generator support - Microsoft/vscode-chrome-debug-core#32
  - [ ] Show Promise state - Microsoft/vscode-chrome-debug-core#33
* Source Maps:
  - [ ] no inlined sources - Microsoft/vscode-chrome-debug-core#85
  - [x] no remote source maps
  - [ ] no local/remote source mapping for remote debugging - Microsoft/vscode-chrome-debug-core#86
  - [ ] Support "dynamically generated sourcemaps" and SystemJS - Microsoft/vscode-chrome-debug-core#36
  - [ ] Smart code stepping - Microsoft/vscode-chrome-debug-core#34
* Misc
  - [ ] completionRequest (intellisense for debug console) - Microsoft/vscode-chrome-debug-core#87
  - [ ] Stop using deprecated 'lines' prop on SetBreakpointsArguments from vscode-debugprotocol - Microsoft/vscode-chrome-debug-core#73
  - [ ] sourceMapPathOverrides matching doesn't work when sourceRoot does not end in / - Microsoft/vscode-chrome-debug-core#78
  - [ ] Minor refactoring to support some features - Microsoft/vscode-chrome-debug-core#57
  - [ ] Add reasons for breakpoint bind failure - Microsoft/vscode-chrome-debug-core#38
  - [ ] Show variable type on hover - Microsoft/vscode-chrome-debug-core#52
  - [ ] Localization - Microsoft/vscode-chrome-debug-core#37
  - [ ] Support function breakpoints - Microsoft/vscode-chrome-debug-core#28
  - [ ] Support callstack paging - Microsoft/vscode-chrome-debug-core#30
  - [ ] Add support for conditional breakpoints - Microsoft/vscode-chrome-debug-core#10
